### ISSUE TITLE
Discounts and Ads addresses and ports should be configurable

### ISSUE THREAD

**Issue by arapulido** [DataDog/ecommerce-workshop#107]
Right now the storefront app has discounts address hardcoded to `discounts:5001` and ads to `advertisements:5002`. Ideally, both the address and ports should be configurable, as this is very specific to the current docker-compose & k8s deployment configuration

**Comment by stevedatadog** [comment]
I ran into a similar issue recently and put this on my whiteboard! I think destiny wants me to take this and #106. What's the due date for 1.1?

**Comment by martinisoft** [comment]
> I ran into a similar issue recently and put this on my whiteboard! I think destiny wants me to take this and #106. What's the due date for 1.1?

No due date set in stone yet. Would be happy to include it into that release.

**Comment by martinisoft** [comment]
Wondering if this should be combined with or considered separate from #13

Any thoughts @arapulido or @stevedatadog?

**Comment by arapulido** [comment]
Yes, this should be combined with #13

**Comment by stevedatadog** [comment]
Agreed.

Steve Calnan

Technical Curriculum Developer

***@***.***
