### ISSUE TITLE
Discount codes should work

### ISSUE THREAD

**Issue by stevedatadog** [DataDog/ecommerce-workshop#109]
Currently, applying a discount code to a shopping cart does not work; the  UI displays a "code not found" error. It would be awesome if storedog actually used the discounts service to reduce checkout totals.

Use case: a synthetic browser test demo that would scrape the code and value from the home page and apply the code to the cart. It would then do the math to confirm that the new cart total is correct.

**Comment by martinisoft** [comment]
I think this is going to require some monkey patching to Spree commerce to make it look at our discounts microservice versus it's own database for discount codes at checkout. Doesn't mean it can't be done, but it'll possibly be a little bit of a hack.

**Comment by stevedatadog** [comment]
I'll make a PR for this in Q1 2022.

**Comment by stevedatadog** [comment]
Closing because the work-to-value ratio is topheavy.
