### ISSUE TITLE
update logging configuration in store-frontend so that Ruby intergration pipeline can be used as is

### ISSUE THREAD

**Issue by shehreendheda** [DataDog/ecommerce-workshop#117]
Current logging configuration requires users to create and update a clone of the Ruby integration pipeline. Need a logging configuration that will work with the OOTB Ruby integration pipeline. (Discussed with Jeremy)

**Comment by mlanci** [comment]
I'm in the middle of trying to set this up to demo to someone within our company. We are interested in metric to log correlation.. Is there a fix to get this working? 

I see the trace and span ID's in the ruby code but not receiving any logs within datadog.

**Comment by shehreendheda** [comment]
@mlanci You should still be able to see logs in DD if log collection is enabled for the service. The issue here is that some of the `http` attributes like `status_code` and `url_path` are in a `payload` attribute group instead. Also, the status code needs to be categorized into severity levels so that the official log status displays the actual log status. (I should have included more details in my original comment.)

**Comment by mlanci** [comment]
Ah understood, apologies for not really being on topic then. I'm deploying on EKS .. and have DD_LOGS_INJECTION set to "true" within the frontend.yaml but not seeing anything.. Not sure what else I could look at to further diagnose the issue.

**Comment by martinisoft** [comment]
> Ah understood, apologies for not really being on topic then. I'm deploying on EKS .. and have DD_LOGS_INJECTION set to "true" within the frontend.yaml but not seeing anything.. Not sure what else I could look at to further diagnose the issue.

@mlanci The DD_LOGS_INJECTION won't work with the frontend side since it is ruby. If you want to try the updated images I would change the image name for the frontend to `ddtraining/storefront:latest` and consider turning on full container log collection if you are installing datadog via HELM. There is some documentation on that in the `deploy/` folder README if you want to instrument everything and collect all logs.

**Comment by mlanci** [comment]
Thank you
