### ISSUE TITLE
RUM 

### ISSUE THREAD

**Issue by jailonso** [DataDog/ecommerce-workshop#12]
Hey team,
I would like to use this demo for a full monitoring workshop including RUM. Would it be possible to implement RUM?
As part of the setup it would be awesome to include as attribute of the session the user email or the amount of items in the cart as in this example:
https://docs.datadoghq.com/real_user_monitoring/installation/advanced_configuration/?tab=npm

**Comment by burningion** [comment]
👋 Real user monitoring is now enabled in the PR mentioned above.
