### ISSUE TITLE
discounts-service or discounts in the k8s yaml files

### ISSUE THREAD

**Issue by technovangelist** [DataDog/ecommerce-workshop#129]
The yaml to load the discounts service is loading the discount-service container which is 10 months old instead of discounts which is 21 days old. Should it be?

**Comment by martinisoft** [comment]
> The yaml to load the discounts service is loading the discount-service container which is 10 months old instead of discounts which is 21 days old. Should it be?

It should definitely not be so that was missed when we switched over the image names. Welcome to submit a PR to update those.
