### ISSUE TITLE
RUM config `env` value should come from environment var

### ISSUE THREAD

**Issue by stevedatadog** [DataDog/ecommerce-workshop#142]
The RUM configuration for Storedog is hardcoded to `production`. Proposal for template (there are a few):

`sed -i 's/production/<%= ENV["DD_ENV"] %>/g' ./store-frontend-instrumented-fixed/store-frontend/app/views/spree/layouts/spree_application.html.erb`

**Comment by stanleegoodspeed** [comment]
@stevedatadog RUM env is now configurable via `DD_ENV` set in the compose file https://github.com/DataDog/ecommerce-workshop/blob/main/deploy/docker-compose/docker-compose-fixed-instrumented-attack.yml#L55
