### ISSUE TITLE
RUM not working

### ISSUE THREAD

**Issue by ivanraposo** [DataDog/ecommerce-workshop#177]
Hello
We have the storedog deployed on GKE. Using the "ecommerce-workshop/deploy/gcp/gke/" ".yaml"'s except the datadog-agent.yaml. The frontend.yaml is configured like this.

![image](https://user-images.githubusercontent.com/92737407/137755138-94799471-c818-44f9-a6fd-60524cae3ddd.png)

But we cant see the RUM on Datadog. We are on the "datadoghq.eu" site.

It would be possible to add the "season replay" too?

Many thanks

**Comment by stanleegoodspeed** [comment]
Hi @ivanraposo , RUM and Session replay should be working now. Please pull down the latest changes from the `main` branch and confirm. You can configure RUM with the following params in the `gke/frontend.yaml`:

https://github.com/DataDog/ecommerce-workshop/blob/main/deploy/gcp/gke/frontend.yaml#L46
```
DD_ENV
DD_SITE
DD_SERVICE
DD_CLIENT_TOKEN
DD_APPLICATION_ID
```

**Comment by ivanraposo** [comment]
Everything working fine. Thank you so much
