### ISSUE TITLE
Hardcoded agent on localhost in advertisements and discounts

### ISSUE THREAD

**Issue by stevedatadog** [DataDog/ecommerce-workshop#180]
Seeing this error a lot from discounts and advertisements in a docker-compose environment. These services do send traces correctly, but something tries to connect to the agent on `localhost` instead of `datadog`, the agent hostname. This results in lots of errors in logs that are distracting.

> ERROR:ddtrace.internal.writer:failed to send traces to Datadog Agent at http://localhost:8126, 2 additional messages skipped

**Comment by stanleegoodspeed** [comment]
@stevedatadog are you seeing this across all compose files?

**Comment by stevedatadog** [comment]
I updated my comment to correct the container hostname the agent is running on.

I'm trying to reproduce this.

**Comment by stevedatadog** [comment]
I'm unable to reproduce this. I'll re-open if I see it again.
