### ISSUE TITLE
Make ads and discounts services XHR compatible

### ISSUE THREAD

**Issue by stevedatadog** [DataDog/ecommerce-workshop#187]
For [this Learning Center RUM scenario](https://github.com/DataDog/LearningLabs/tree/main/snippets/rumcwv), we hacked Storedog to fetch ads and discounts async via XHR. This required adding CORS to those services. This would be useful as a permanent feature.

See `assets/discounts.py` and `assets/ads.py` for the minor changes necessary.

**Comment by stanleegoodspeed** [comment]
@stevedatadog this should be all set now
