### ISSUE TITLE
Update/correct logging for store-frontend

### ISSUE THREAD

**Issue by shehreendheda** [DataDog/ecommerce-workshop#61]
Extra log line are ingested and displayed in DD Logs UI for the store-frontend. Chatted with Aaron and he says that logging needs to be updated for the service. 

Example of logs for fixed store-frontend:
<img width="943" alt="basev1-fixed-frontend" src="https://user-images.githubusercontent.com/25783180/106183090-a21eb280-6154-11eb-81d5-5636dda32cff.png">

Example of logs for broken store-frontend:
<img width="946" alt="basev1-broken-frontend" src="https://user-images.githubusercontent.com/25783180/106183144-b662af80-6154-11eb-8f54-bc9d6232c42c.png">

**Comment by shehreendheda** [comment]
Also noticed that the logs that are being processed (log lines with content `duration...`) have `http.status_code: 200` or `http.status_code: 500`, but the official log status in DD is `INFO`. For the Ruby Integration Pipeline, log status is mapped to the attribute `level`. 

<img width="720" alt="Screen Shot 2021-02-08 at 9 04 48 AM" src="https://user-images.githubusercontent.com/25783180/107255547-458d8400-69ed-11eb-847c-a9c361ff0ea1.png">

Can logging in the app include categorizing `http.status_code` into a `level` attribute? Categories like the ones below or whatever would make sense for the app.
| Category | Level |
| -------- | ---- |
| http.status_code:[200 TO 299] | ok |
| http.status_code:[300 TO 399] | notice |
| http.status_code:[400 TO 499] | warning |
| http.status_code:[500 TO 599] | error |

**Comment by martinisoft** [comment]
After more than a few rounds of local testing, I think lograge as we prescribe does not cover all cases for logging and thus we will _probably_ want to update the docs to cover this particular case. Lograge is built around covering request logs, but doesn't cover caching or SQL queries for example which you point to up there. Even our own advice by default does not cover severity either so I will try to make some quick patches for now, but figure out a longer term solution with our ruby folks to see if there is a better out of the box method here.

**Comment by martinisoft** [comment]
I am now exploring using [semantic logger](https://github.com/rocketjob/semantic_logger) to replace lograge. If it works, I will probably discuss with the docs and logs teams to see if we can shift our recommendations to that solution since it is more actively maintained and might have a better out of the box experience.

**Comment by martinisoft** [comment]
This is the furthest I can reasonably go in cutting down the logging noise right now 
![image](https://user-images.githubusercontent.com/724/109999221-9dab6380-7cd7-11eb-8979-6d898f506ee7.png)

Once we can ship the default logs changes internally, I can do a fresh PR to switch us to [semantic logger](https://github.com/rocketjob/semantic_logger) which will help a lot for formatting all the log messages correctly and work out of the box better.

**Comment by martinisoft** [comment]
This is now resolved by #80
