### ISSUE TITLE
Errors in discounts/ads not logging properly

### ISSUE THREAD

**Issue by shehreendheda** [DataDog/ecommerce-workshop#65]
Noticed that the exceptions in the python services are not being logged as a single line. Seeing that APM captures the exception properly but the log gets split across multiple lines.

<img width="1052" alt="Screen Shot 2021-02-02 at 10 20 35 AM" src="https://user-images.githubusercontent.com/25783180/106781084-82c4d100-65fd-11eb-8057-938ff985c3e4.png">

**Comment by martinisoft** [comment]
I have shipped newer built containers for the ads service in #64 which should be up on Dockerhub under `ddtraining/advertisements` and `ddtraining/advertisements-fixed` respectively. If you update the docker-compose file for those container names and run them that should work a little better. I'll be checking up internally to see if there might be anything I am missing for the logging formatter.

**Comment by shehreendheda** [comment]
Errors are being logged correctly now. 
<img width="632" alt="Screen Shot 2021-02-16 at 10 50 23 AM" src="https://user-images.githubusercontent.com/25783180/108108099-02628f00-7045-11eb-8259-da1141d0799f.png">
