### ISSUE TITLE
Add attack container

### ISSUE THREAD

**Issue by andrewkrug** [DataDog/ecommerce-workshop#71]
As a course developer in the datadog training platform I can access a Kali Linux or similar container with attack tools.  The container should feature flag spin up with the rest of the environment and provide the ability to run specific automation.  

- [ ] Brute force attack 
- [ ] Dirbuster

The container bootstrap should be such that we can extend the number of attacks and containers impacted.

**Comment by burningion** [comment]
This attack container should consist of two binaries so far:

[gobuster](https://github.com/OJ/gobuster) and [hydra](https://github.com/vanhauser-thc/thc-hydra#where-to-get). 

This should also fix issue #74, unless we decide to have an instrumented version of logs, _without_ proper parsing.

**Comment by andrewkrug** [comment]
The attack container will also at some point after spin up need to do the following using a bash script.  Use a leaked ssh-key ( bootstrapped with the environment ) in order to sign into one system running sshd and plant a new authorized_key.  Then after some time wipe /var/log/secure log and zero out the unallocated space on the disk ( 10MB lets say ) using ``sudo dd if=/dev/zero of=tempfile bs=1m count=10``.  This will probably require adding sshd, an unprivileged user, sudo, and the dd binary to a system in the infrastructure.

**Comment by martinisoft** [comment]
> The attack container will also at some point after spin up need to do the following using a bash script. Use a leaked ssh-key ( bootstrapped with the environment ) in order to sign into one system running sshd and plant a new authorized_key. Then after some time wipe /var/log/secure log and zero out the unallocated space on the disk ( 10MB lets say ) using `sudo dd if=/dev/zero of=tempfile bs=1m count=10`. This will probably require adding sshd, an unprivileged user, sudo, and the dd binary to a system in the infrastructure.

So this container needs to access another one in the cluster? Trying to figure out some implementation details here. The automation part sounds like a challenge given the ways we can deploy this system. My guess is we have to aim for docker-compose as the deploy/trigger mechanism since it'll be in Katacoda yes?

**Comment by stevedatadog** [comment]
I think we can close this, @andrewkrug ?
